### ISSUE TITLE
Blogging platform

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/wiki#10]
This looks like a pretty decent option: https://liang2kl.github.io/mkdocs-blogging-plugin/

(the other option is paying for the material-mkdocs plugin)

**Comment by tshiunghan** [comment]
I took a look at the docs and it looks really clean. Could you install it and I'll play around with it?

**Comment by simonv3** [comment]
This is done. The blog shows the [latest four posts](https://github.com/funmusicplace/wiki/blob/main/mkdocs.yml#L36) on the main page and blog posts are also accessible through the menu. You can see a published [post here](https://funmusic.place/blog/the-spotify-ai-blues/) and see them [on GitHub here](https://github.com/funmusicplace/wiki/tree/main/docs/blog). The "Edit This Page" button should also be available for any blog post.  

Main thing to note is that I don't think there's a way to manually set the publish date. I think it's based on the date of the git commit. That's a little frustrating.
